
exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('group_member').del(),

    // Inserts seed entries
    knex('group_member').insert({id: 1,
      group_id: 1,
      member_id: 1}),
    knex('group_member').insert({id: 2,
      group_id: 1,
      member_id: 2}),
    knex('group_member').insert({id: 3,
      group_id: 1,
      member_id: 3}),
    knex('group_member').insert({id: 4,
      group_id: 1,
      member_id: 4}),
    knex('group_member').insert({id: 5,
      group_id: 1,
      member_id: 5}),
    knex('group_member').insert({id: 6,
      group_id: 1,
      member_id: 6}),
    knex('group_member').insert({id: 7,
      group_id: 1,
      member_id: 7}),
    knex('group_member').insert({id: 8,
      group_id: 2,
      member_id: 8}),
    knex('group_member').insert({id: 9,
      group_id: 2,
      member_id: 9}),
    knex('group_member').insert({id: 10,
      group_id: 2,
      member_id: 10}),
    knex('group_member').insert({id: 11,
      group_id: 2,
      member_id: 11}),
    knex('group_member').insert({id: 12,
      group_id: 2,
      member_id: 12}),
    knex('group_member').insert({id: 13,
      group_id: 2,
      member_id: 13}),
    knex('group_member').insert({id: 14,
      group_id: 2,
      member_id: 14}),
    knex('group_member').insert({id: 15,
      group_id: 3,
      member_id: 15}),
    knex('group_member').insert({id: 16,
      group_id: 3,
      member_id: 16}),
    knex('group_member').insert({id: 17,
      group_id: 3,
      member_id: 17}),
    knex('group_member').insert({id: 18,
      group_id: 3,
      member_id: 18}),
    knex('group_member').insert({id: 19,
      group_id: 3,
      member_id: 19}),
    knex('group_member').insert({id: 20,
      group_id: 3,
      member_id: 20}),
    knex('group_member').insert({id: 21,
      group_id: 3,
      member_id: 21}),
    knex('group_member').insert({id: 22,
      group_id: 3,
      member_id: 22}),
    knex('group_member').insert({id: 23,
      group_id: 3,
      member_id: 23})
  );
};
